apiVersion: v1
kind: Service
metadata:
  name: reactapp-port
  labels:
    app: reactapp
spec:
  selector:
    app: reactapp
  type: NodePort
  ports:
  - name: http
    port: 8082
    targetPort: 80
    protocol: TCP
    nodePort: 32001