apiVersion: apps/v1
kind: Deployment
metadata:
  name: gradle-api-deployment
  labels:
    app: gradle-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gradle-api
  template:
    metadata:
      labels:
        app: gradle-api
    spec:
      containers:
      - name: gradle-api
        image: gradle-api:v1.0.1
        ports:
        - containerPort: 8183