apiVersion: v1
kind: Service
metadata:
  name: gradle-api-port
  labels:
    app: gradle-api
spec:
  selector:
    app: gradle-api
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 8183
    protocol: TCP
    nodePort: 32020
