apiVersion: v1
kind: Service
metadata:
  name: gradle-api
spec:
  selector:
    app: gradle-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8183
  type: ClusterIP