apiVersion: v1
kind: Service
metadata:
  name: mssql
  labels:
    app: mssql
spec:
  selector:
    app: mssql
  ports:
    - name: mssql
      port: 1433
      targetPort: 1433
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mssql
spec:
  serviceName: mssql
  replicas: 3
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      containers:
      - name: mssql
        image: mcr.microsoft.com/mssql/server:latest
        env:
          - name: ACCEPT_EULA
            value: Y
          - name: SA_PASSWORD
            value: YourStrongPassword
        ports:
        - containerPort: 1433
          name: mssql
        volumeMounts:
          - name: mssql-data
            mountPath: /var/opt/mssql/data
      volumes:
        - name: mssql-data
          persistentVolumeClaim:
            claimName: mssql-pvc
  volumeClaimTemplates:
  - metadata:
      name: mssql-pvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi