apiVersion: v1
kind: Service
metadata:
  name: webapi-port
  labels:
    app: webapi
spec:
  selector:
    app: webapi
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
    nodePort: 32000
