apiVersion: v1
kind: Service
metadata:
  name: webapi-service
  labels:
    app: webapi
spec:
  type: ClusterIP
  selector:
    app: webapi
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 80